config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'

  get 'answers/edit'

  get "/profile" => "custom_users#profile"
  devise_for :users do 
  end

  resources :questions do 
          resources :answers do 
                  member do 
                          put "up" 
                          put "down"
                  end
          end

          resources :comments

          member do 
                  put "up" 
                  put "down"
          end
  end

  resources :answers do
          resources :comments

  end

  root "questions#index"

end

app/models/question.rb
class Question < ActiveRecord::Base
        belongs_to :user
        has_many :answers
        has_many :comments, as: :commentable
        has_many :votes, as: :votable

        validates :title, presence: true, length: {in: 5..255}
        validates :content, presence: true, length: {in: 5..1000}
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

        before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :up, :down]
        before_action :find_question, only: [:show, :edit, :update, :destroy, :up, :down]
        before_action :check_question_with_user, only: [:edit, :destroy]

        def index
                @questions = Question.includes(:user).all
        end

        def show
        end

        def new
                @question = Question.new
        end

        def create
                @question = Question.new question_params
                @question.user = current_user
                if @question.save
                        redirect_to @question
                else
                        render :new
                end
        end

        def edit
        end

        def update
               if @question.update(question_params)
                       redirect_to @question, notice: "update question successfully"
               else
                       render :edit
               end
        end

        #can coi lai
        def destroy
                #clear all dependent before delete question
                @question.answers.destroy_all
                @question.comments.destroy_all
                @question.votes.destroy_all
                
                @question.destroy

                redirect_to profile_path
        end


        def up
                #check whether or not user already voted this question
                @vote = @question.votes.where(user: current_user).first
                if !@vote
                        @vote = Vote.create(votable: @question, user: current_user, vote_up: true)
                else
                        @vote.update(vote_up: true)
                end
                redirect_to @question, notice: "Vote up successfully"
        end

        def down
                # byebug
                #check whether or not user already voted this question
                @vote = @question.votes.where(user: current_user).first
                if !@vote
                        @vote = Vote.create(votable: @question, user: current_user, vote_up: false)
                else
                        @vote.update(vote_up: false)
                end
                redirect_to @question, notice: "Vote down successfully"
        end




        def question_params
                params.require(:question).permit(:title, :content)
        end

        def find_question
                @question = Question.find(params[:id])
        end

        def check_question_with_user
                if @question.user != current_user
                        redirect_to root_path
                end
        end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/questions/index.html.erb
<h1>List questions</h1>
<%= link_to "Add new question", new_question_path %>
<hr>
<div class="questions-container">

        <% @questions.each do  |question|%>
                <div class="question">
                        <div class="content">
                                <%= link_to question.title, question_path(question)%>
                        </div>
                        <div class="some-info">
                                by <%= question.user.email%> at <i style="color: gray;"><%= time_ago_in_words(question.updated_at)%></i>
                        </div>
                </div>
                <hr>
        <% end %>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/questions/show.html.erb
<div class="question">
        <h2><%=  @question.title%></h2>
        <h4>Asked by <%= @question.user.email %></h4>
        <br>
        <div>
                <%= @question.content %>

                <div class="votes" style="overflow:hidden;margin-top: 20px;">
                        <div class="vote-up" style="float:left;">
                                <% if user_signed_in? %>
                                        <%= link_to "Vote up", up_question_path(@question), method: :put %>
                                <% else %>
                                        <span style="color: green;">Vote up</span>
                                <% end %>

                                <span><%= @question.votes.where(vote_up: true).count%></span>
                        </div>
                        <div class="vote-down" style="float:left; margin-left: 20px;">
                                <% if user_signed_in? %>
                                        <%= link_to "Vote down", down_question_path(@question), method: :put %>
                                <% else %>
                                        <span style="color: red;">Vote down</span>
                                <% end %>
                                <span><%= @question.votes.where(vote_up: false).count %></span>
                        </div>
                </div>
        </div>


        <hr>
        <div class="comments-container" style="margin-left: 100px;">
                <%= link_to "Comment this question", new_question_comment_path(@question) %>
                <hr>
                <div class="list-comments">
                        <h3><%= @question.comments.count%> Comments</h3>
                        <% @question.comments.includes(:user).each do |comment|%>
                                <div class="comment">
                                        <h4><%=comment.user.email%> at <i style="color: gray;"><%= time_ago_in_words(comment.updated_at)%></i></h4>
                                        <div class="content">
                                                <%= comment.content%>
                                        </div>
                                        <div class="action">
                                                <% if comment.user == current_user %>
                                                        <%= link_to "Edit", edit_question_comment_path(@question, comment) %>
                                                        <%= link_to "Delete", question_comment_path(@question, comment), method: :delete, data: { confirm: 'Are you sure?' }%>
                                                <% end %>
 
                                        </div>
                                </div>
                                <hr>
                        <% end %>
                </div>
        </div>
</div>

<div class="answers-container">
        <hr>
        <%= link_to "Answer this question", new_question_answer_path(@question) %>
        <hr>

        <h3><%= @question.answers.count%> Answers</h3>
        <% if @question.answers.empty? %>
                <h4>Empty</h4>
        <% end %>

        <% @question.answers.includes(:votes, :user, comments: [:user]).each do |answer| %>

                <div class="answer">
                        <p><%= answer.user.email%></p>
                        <p><%= answer.content %></p>
                        <% if answer.user == current_user %>
                                <%= link_to "Edit", edit_question_answer_path(@question, answer) %>
                                <%= link_to "Delete", question_answer_path(@question, answer), method: :delete, data: { confirm: 'Are you sure?' }%>
                        <% end %>

                        <!-- begin for vote up and down  answers -->
                        <div class="votes" style="overflow:hidden;margin-top: 20px;">
                                <div class="vote-up" style="float:left;">
                                        <% if user_signed_in? %>
                                                <%= link_to "Vote up", up_question_answer_path(@question, answer), method: :put %>
                                        <% else %>
                                                <span style="color: green;">Vote up</span>
                                        <% end %>

                                        <span><%= answer.votes.where(vote_up: true).count%></span>
                                </div>
                                <div class="vote-down" style="float:left; margin-left: 20px;">
                                        <% if user_signed_in? %>
                                                <%= link_to "Vote down", down_question_answer_path(@question, answer), method: :put %>
                                        <% else %>
                                                <span style="color: red;">Vote down</span>
                                        <% end %>
                                        <span><%= answer.votes.where(vote_up: false).count %></span>
                                </div>
                        </div>
                        <!-- end for vote up and down  answers -->

                        <!-- begin list comment for answers -->
                        <hr>
                        <div class="comments-container" style="margin-left: 100px;">
                                <%= link_to "Comment this answer", new_answer_comment_path(answer) %>
                                <hr>
                                <div class="list-comments">
                                        <h3><%= answer.comments.count%> Comments</h3>
                                        <% answer.comments.each do |comment|%>
                                                <div class="comment">
                                                        <h4><%=comment.user.email%> at <i style="color: gray;"><%= time_ago_in_words(comment.updated_at)%></i></h4>
                                                        <div class="content">
                                                                <%= comment.content%>
                                                        </div>
                                                        <div class="action">
                                                                <% if comment.user == current_user %>
                                                                        <%= link_to "Edit", edit_answer_comment_path(answer, comment) %>
                                                                        <%= link_to "Delete", answer_comment_path(answer, comment), method: :delete, data: { confirm: 'Are you sure?' }%>
                                                                <% end %>

                                                        </div>
                                                </div>
                                                <hr>
                                        <% end %>
                                </div>
                        </div>
                </div>
                <hr>
        <% end %>
</div>
<!-- <script type="text/javascript" charset="utf&#45;8"> -->
<!--         console.log("in javascript"); -->
<!--         $(document).ready(function(){ -->
<!--  -->
<!--                 alert("ready"); -->
<!--         }); -->
<!-- </script> -->