config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'

  get 'answers/edit'

  get "/profile" => "custom_users#profile"
  devise_for :users do 
  end

  resources :questions do 
          resources :answers do 
                  member do 
                          put "up" 
                          put "down"
                  end
          end

          resources :comments

          member do 
                  put "up" 
                  put "down"
          end
  end

  resources :answers do
          resources :comments

  end

  root "questions#index"

end

app/controllers/custom_users_controller.rb
class CustomUsersController < ApplicationController
        before_action :authenticate_user!, only: [:profile]

        def profile
                @questions = current_user.questions
                @answers = current_user.answers.includes(:question)
        end
end

app/views/custom_users/profile.html.erb
<h1>List questions asked</h1>
<ul>
        <% @questions.each do |question|%>
                <li>
                <%= question.title %> 
                <%= link_to "Edit", edit_question_path(question)%>
                <%= link_to "Delete", question_path(question), method: :delete, data: { confirm: 'Are you sure?' } %>
                </li>
                <hr>
        <% end %>
</ul>

<hr>

<h1>List answer that you answered</h1>
<ul>
        <% @answers.each do |answer|%>
                <li>
                <%= answer.content %> | for <%= answer.question.title %>
                <%= link_to "Detail", question_path(answer.question)%>
                </li>
                <hr>
        <% end %>
</ul>