config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'

  get 'answers/edit'

  get "/profile" => "custom_users#profile"
  devise_for :users do 
  end

  resources :questions do 
          resources :answers do 
                  member do 
                          put "up" 
                          put "down"
                  end
          end

          resources :comments

          member do 
                  put "up" 
                  put "down"
          end
  end

  resources :answers do
          resources :comments

  end

  root "questions#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStackoverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

        <%= link_to "Home", root_path %>
        <% if !user_signed_in? %>
                <%= link_to "Sign up", new_user_registration_path %>
                <%= link_to "Sign in", new_user_session_path %>
        <% else %>

                <%= link_to current_user.email, profile_path%>
                <%= link_to "Logout", destroy_user_session_path, method: :delete%>
        <% end %>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
        <%= yield %>

        <style type="text/css" media="screen">
                
                .notice{
                        color: green;
                }
                .alert{
                        color: red;
                }
        </style>
</body>
</html>